### ISSUE TITLE
Computing growth using built-in PRESCIENT commands for mouse scRNA-seq data

### ISSUE THREAD

**Issue by YangLi-Bio** [gifford-lab/prescient#4]
I have been analyzing a mouse dataset using Prescient. One step is calculating growth using birth (KEGG_CELL_CYCLE) and death (KEGG_APOPTOSIS) pathway information. I wonder whether I can use this human pathway information on mouse data.

Thank you!

**Comment by sachitsaksena** [comment]
Thanks for using the method and reaching out! We actually applied PRESCIENT to a mouse dataset in our publication and the relevant gene lists are provided here (although you could test out your own too!): [https://zenodo.org/record/4687963#.YzYSPezMLFw](Zenodo.). Specifically, the mouse gene signatures are located at `/data/Weinreb2020_fate/birth_msigdb_kegg.csv` and `/data/Weinreb2020_fate/death_msigdb_kegg.csv`. You would use these when calculating growth using the provided function `prescient.utils.get_growth_weights()` replacing the "birth_gst" and "death_gst" arguments with paths to these files. Here is an [https://github.com/gifford-lab/prescient/blob/master/notebooks/estimate-growth-rates.ipynb](example).

**Comment by YangLi-Bio** [comment]
Thank you very much!
