### ISSUE TITLE
init_task function in the prescient > train > run.py undefined.

### ISSUE THREAD

**Issue by DabinJeong** [gifford-lab/prescient#7]
Hi, I inspected the code to get insight on how gene exp. profile of cells is fed into the model as an input.
However, "init_task" function is not defined in none of the relevant scripts. 
![20230523_172030](https://github.com/gifford-lab/prescient/assets/32008468/b8b2a97f-4cd9-494c-8047-25c7b5d233eb)
Could you provide the source code of the "init_task" function or specify where the source code resides? Thanks!

**Comment by ekernf01** [comment]
I think the function that gets passed to this is `train_init` defined in `prescient/commands/train_model.py` line 112.

**Comment by sachitsaksena** [comment]
Apologies for missing this - @ekernf01 is correct. Thanks for addressing it!
