### ISSUE TITLE
Celltype is missing from the description of the format of PRESCIENT torch object

### ISSUE THREAD

**Issue by nekonekko** [gifford-lab/prescient#9]
Hello. I noticed a lack of information in the documentation. This may be a minor issue, but I would like to report it just in case.

In the PRESCIENT torch object section of the [input page](https://cgs.csail.mit.edu/prescient/file_formats/) on [your documentation site](https://cgs.csail.mit.edu/prescient/index), `data_pt["celltype"]` is missing.

I noticed this when I was manually creating PRESCIENT torch objects.

The `data.pt` generated via the `process_data` command contained `celltype`, so I assumed that `celltype` was a necessary key and was just missing from the documentation.

Could you take a look at it when you have time? Thank you.

**Comment by sachitsaksena** [comment]
Thank you for identifying this! `celltype` is only necessary for certain analyses but is useful to include in documentation. Addressed here: https://github.com/gifford-lab/prescient/commit/fd4094e4a4cac17cddb528f61eda2756290e3585
